FrontEnd/ias_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Leave empty to set as home page
    path('', include('socialgraph.urls')),
]

FrontEnd/socialgraph/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='socialgraph-home'),
    path('users/', views.users, name='socialgraph-users'),
    # path('about/', views.about, name='socialgraph-about'),
    # path('Feed/', views.feed, name='socialgraph-feed'),
    path('profile/<pk>/', views.PostDetailView.as_view(), name='profile-detail'),
    path('profile-update/', views.update_profile, name='profile-update'),
    path('Follow/', views.follow, name ='socialgraph-follow'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FrontEnd/socialgraph/models.py
__author__ = "Philipp Haller, Pascal Kunz, Sebastian Schlachter"
'''This file defines all models and there functions in the used database.'''

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
import datetime

class Status(models.Model):
    """This is needed to create multiple instances of status, one Profile can then have a relation to multiple
    status (The Current and all the old ones)."""
    timestamp = models.DateTimeField(blank=True, null=True, default=None)
    status = models.CharField(max_length=256, blank=True, null=True, default=None)


class Profile(models.Model):
    """Each entry stores the information of one nodes/users Profile Page."""
    bacnet_id = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    gender = models.CharField(max_length=6, blank=True, null=True, default=None)
    birthday = models.DateField(blank=True, null=True, default=None)
    country = models.CharField(max_length=64, blank=True, null=True, default=None)
    town = models.CharField(max_length=64, blank=True, null=True, default=None)
    language = models.CharField(max_length=256, blank=True, null=True, default=None)
    profile_pic = models.ImageField(default='default.jpg', upload_to='profile_pics')
    myself = models.BooleanField(default=False)
    node_id = models.IntegerField(primary_key=True)
    status = models.CharField(max_length=256, blank=True, null=True, default=None)
    follows = models.ManyToManyField('self', symmetrical=False)
    status_list = models.ManyToManyField(Status, symmetrical=False)
    influencer = models.BooleanField(default=False)

    def __str__(self):
        """Defines the string representation"""
        return f'{self.name} Profile / {self.bacnet_id}'

    def get_details(self):
        """Returns a hashmap containing the attributes (of this database entry) that should be displayed on the profile
        page. """
        details = {}
        if self.gender is not None:
            details['Gender']= self.gender
        if self.birthday is not None:
            details['Birthday']= self.birthday
        if self.country is not None:
            details['Country']= self.country
        if self.town is not None:
            details['Town']= self.town
        if self.language is not None:
            details['Language']= self.language
        return details

class FollowRecommendations(models.Model):
    layer = models.IntegerField(default=None)
    bacnet_id = models.CharField(max_length=64, primary_key=True)
    id = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    gender = models.CharField(max_length=6, blank=True, null=True, default=None)
    birthday = models.DateField(blank=True, null=True, default=None)
    age = models.IntegerField(default=None)
    influencer = models.BooleanField(blank=True, null=True, default=None)
    country = models.CharField(max_length=64, blank=True, null=True, default=None)
    town = models.CharField(max_length=64, blank=True, null=True, default=None)
    language = models.CharField(max_length=256, blank=True, null=True,
                                default=None)
    profile_pic = models.ImageField(default='default.jpg', upload_to='profile_pics')
    levenshteinDistName = models.IntegerField(default=None)
    levenshteinDistTown = models.IntegerField(default=None)

FrontEnd/socialgraph/views.py
__author__ = "Philipp Haller, Pascal Kunz, Sebastian Schlachter"

import json
import os
import pathlib
from pathlib import Path
import pdb
import sys

from django.http import HttpResponseRedirect
from django.shortcuts import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import DetailView

from .importer import create_profiles, create_Recommendations
from .models import Profile, FollowRecommendations
from .utils.jsonUtils import extract_connections, getRoot, getRootFollowsSize, getRootFollowersSize, saveSettings
from django.db.models import F
from django.db.models import Min, Max
import Levenshtein

x = os.getcwd()
from .utils.callToBackend import followCall, unfollowCall, profileUpdateCall

os.chdir(x)

# Create your views here.

path = pathlib.Path('socialgraph/static/socialgraph/')
path2 = path / 'testData.json'
path = path / 'loadedData.json'
# path = path / 'loadedData1.json'

data_file = open(path)
data = json.load(data_file)
data_file.close()

settingsPath = Path('socialgraph/static/socialgraph/')
settingsPath = settingsPath / 'settings.json'
settings_data_file = open(settingsPath)
settings_data = json.load(settings_data_file)
settings_data_file.close()


def home(request):
    x = pathlib.Path(__file__)
    print(x.parent.parent)
    os.chdir(x.parent.parent)
    data_file = open(path)
    data = json.load(data_file)
    data_file.close()
    root = getRoot(data['nodes'])
    follows = getRootFollowsSize(data['links'], root.get("id"))
    followers = getRootFollowersSize(data['links'], root.get("id"))

    settings_data_file = open(settingsPath)
    settings_data = json.load(settings_data_file)
    settings_data_file.close()

    if request.method == "POST":
        response = request.POST['text']
        newSettings = saveSettings(settings_data, response, settingsPath)
        return HttpResponse(newSettings)

    context = {
        'connections': extract_connections(data, "1 1"),
        'root': root,
        'follows': follows,
        'followers': followers,
        'all': len(data['nodes']),
        'activity': root.get("activity level"),
        'influencer': root.get("influencer"),
        'graph': settings_data
    }

    return render(request, 'socialgraph/home.html', context)


def users(request):
    x = pathlib.Path(__file__)
    print(x.parent.parent)
    os.chdir(x.parent.parent)
    data_file = open(path)
    data = json.load(data_file)
    data_file.close()
    root = getRoot(data['nodes'])

    settings_data_file = open(settingsPath)
    settings_data = json.load(settings_data_file)
    settings_data_file.close()

    if request.method == "POST":
        response = request.POST['text']
        j = extract_connections(data, response)
        return HttpResponse(j)

    context = {
        'data': json.dumps(data),
        'root': root,
        'nodes': sorted(data['nodes'], key=lambda item: item["hopLayer"]),
        'links': data['links'],
        'graph': settings_data
    }
    create_profiles(data)
    return render(request, 'socialgraph/users.html', context)


def reloadJson():
    x = pathlib.Path(__file__)
    os.chdir(x.parent.parent)
    data_file = open(path)
    data = json.load(data_file)
    data_file.close()
    return data

"""
Handle UserInputs coming from the Follow / Unfollow GUI.
"""
def follow(request):
    data = reloadJson()
    create_Recommendations(data)
    #Initial QuerySet
    querySetFollow = FollowRecommendations.objects.filter(layer__gte = 2)
    # create a context variable, will be passed to the render of the Follow GUI
    context = {
        'data': json.dumps(data),
        'nodes': data['nodes'],
        'links': data['links'],
        'recommendations': querySetFollow
    }

    # In case we have received an Ajax call from the UI-Layer:
    if request.method == "POST":
        # Get the values of the Ajax call
        response = request.POST.get('text', False)
        mode = request.POST.get('mode', False)
        layer = int(request.POST.get('layer', False))
        influencer = request.POST.get('influencer', False)
        gender = request.POST.get('gender', False)
        ageLower = request.POST.get('ageLower', False)
        ageUpper = request.POST.get('ageUpper', False)
        name = request.POST.get('name', False)
        town = request.POST.get('town', False)

        if (influencer == "false"):
            influencer = "ignore"
        else:
            influencer = True
        #If we are in the follow mode:
        if(mode == "1follow"):
            if layer == 0:
                layer = 1
            query_values = {'layer': layer,
                           'influencer': influencer, 'gender':gender,
                            'age__gte': ageLower, 'age__lte':ageUpper,
                            }
            #Create the arguments for the SQL-Query
            arguments = {}
            for k, v in query_values.items():
                if ((v and v != "all" and v!= "ignore" and v != 1) or (k == 'influencer' and v == True)):
                    arguments[k] = v
            if (layer == 1):
                querySet = FollowRecommendations.objects.filter(**arguments).filter(layer__gte =2)
            else:
                querySet = FollowRecommendations.objects.filter(**arguments)
            #User has reset the filters
            if (response == "reset"):
                querySet = FollowRecommendations.objects.all()
            # User wants to follow another user
            elif (response.startswith("fo")):
                root = getRoot(data['nodes'])
                rootUser = root.get("name")
                rootUserID = root.get("BACnetID")
                followID = str(response[2:18])
                followName = str(response[18:len(response)])
                followCall(mainPersonName=rootUser, mainPersonID=rootUserID, followPersonName=followName,
                           followPersonID=followID)

                data = reloadJson()
                #Update entry in database
                entry = FollowRecommendations.objects.filter(bacnet_id=followID)
                entry.update(layer = 1)
                query_values = {'layer': layer,
                               'influencer': influencer, 'gender': gender,
                               'age__gte': ageLower, 'age__lte': ageUpper,
                               }
                arguments = {}
                for k, v in query_values.items():
                    if ((v and v != "all" and v != "ignore" and v != 1) or (k == 'influencer' and v == True)):
                        arguments[k] = v
                if (layer == 1):
                    querySet = FollowRecommendations.objects.filter(**arguments).filter(layer__gte=2)
                else:
                    querySet = FollowRecommendations.objects.filter(**arguments)
            #Filter with levenshtein if name or town is filled out.
            querySet = filterWithLevenshtein(querySet, name, town)


            text = {
                'data': json.dumps(data),
                'nodes': data['nodes'],
                'links': data['links'],
                'recommendations': querySet
            }

            return render(request, 'socialgraph/FollowBody.html', text)
        #if we are in the unfollow mode
        if (mode == "1unfollow"):
            query_values = {'influencer': influencer, 'gender': gender,
                            'age__gte': ageLower, 'age__lte': ageUpper,
                            }
            arguments = {}
            for k, v in query_values.items():
                if ((v and v != "all" and v != "ignore") or (k == 'influencer' and v == True)):
                    arguments[k] = v
            querySet = FollowRecommendations.objects.filter(**arguments).filter(layer = 1)
            #User has reset the filters
            if (response == "reset"):
                querySet = FollowRecommendations.objects.filter(layer =1)
            # User wants to follow another user
            if (response.startswith("uf")):
                root = getRoot(data['nodes'])
                rootUser = root.get("name")
                rootUserID = root.get("BACnetID")
                unfollowID = str(response[2:18])
                unfollowName = str(response[18:len(response)])
                unfollowCall(mainPersonName=rootUser, mainPersonID=rootUserID, unfollowPersonName=unfollowName,
                             unfollowPersonID=unfollowID)
                data = reloadJson()
                create_Recommendations(data)
                query_values = {'layer': 1, 'influencer': influencer,
                                'gender': gender, 'age__gte': ageLower,
                                'age__lte': ageUpper}
                arguments = {}
                for k, v in query_values.items():
                    if ((v and v != "all" and v != "ignore") or (k == 'influencer' and v == True)):
                        arguments[k] = v
                querySet = FollowRecommendations.objects.filter(**arguments).filter(layer = 1)

            querySet = filterWithLevenshtein(querySet, name, town)

            text = {
                'data': json.dumps(data),
                'nodes': data['nodes'],
                'links': data['links'],
                'recommendations': querySet
            }
            return render(request, 'socialgraph/UnfollowBody.html', text)
    return render(request, 'socialgraph/Follow.html', context)

def addLevenshtein(name, mode):
    if (name == ""):
        return
    if mode == "name":
        for entry in FollowRecommendations.objects.filter():
            entry.levenshteinDistName = Levenshtein.distance(entry.name, name)
            entry.save()
    else:
        for entry in FollowRecommendations.objects.filter():
            entry.levenshteinDistTown = Levenshtein.distance(entry.town, name)
            entry.save()

def filterWithLevenshtein(querySet,name,town):

FrontEnd/socialgraph/templates/socialgraph/Feed.html
{% extends "socialgraph/base.html" %}
{% block content %}

  <div class="container">
      <h4 class="content-section-title">Feed</h4>

      <div class="content-section" id="feedContentSection">


      </div>
  </div>

{% endblock content %}

FrontEnd/socialgraph/templates/socialgraph/FollowBody.html
<ul class="list" id = 'test'>
{% for person in recommendations %}

    <li class="list-item" id = listEl data-link="{% url 'profile-detail' person.id %}">
        <div>
            <img src="{{person.profile_pic.url}}" class="list-item-image" >
        </div>

        <div class="list-item-content" >

            <h4>{{person.name}}</h4>
            <p>{{person.gender}}</p>
            <p>{{person.age}}</p>
            <p>{{person.town}}</p>

            <p>   </p>

            <button class="followButton" id = "button" onclick=follow("{{person.bacnet_id}}","{{person.name}}")>
                Follow!
            </button>

        </div>

    </li>

      {% endfor %}

</ul>


<script>

    function follow(bacnetID, name){
       $('.list-item').off('click');
        var gender = getGender();
        var mode = getMode();
        var layer = getLayer();
        var nameIn = getname();
        var Town = getTown();
        var influencer = getInfluencerChecked();
        var al;
        var au;
        if (ageLower() === "")
            al = 0;
        else
            al = document.getElementById('ageMin').value
        if (ageUpper() === "")
            au = 120
        else
            au = document.getElementById('ageMax').value


        $.ajax({

                type: "POST",
                url: '{{ '' }}',
                async: false,
                data: {csrfmiddlewaretoken: '{{ csrf_token }}', text: "fo"+bacnetID+name, gender : gender, mode: mode, layer : layer, name: nameIn, town : Town, influencer : influencer, ageLower : al, ageUpper : au},
                success: function (response){
                    $('#test').html('').replaceWith(response)

                }

            });
    }



    $(".list-item").click(function() {
        location.href = $(this).data('link');
    })











</script>

FrontEnd/socialgraph/templates/socialgraph/UnfollowBody.html
<ul class="list" id = 'test'>
{% for person in recommendations %}

    <li class="list-item" id = listEl data-link="{% url 'profile-detail' person.id %}">
        <div>
            <img src="{{person.profile_pic.url}}" class="list-item-image" >
        </div>

        <div class="list-item-content" >

            <h4>{{person.name}}</h4>
            <p>{{person.gender}}</p>
            <p>{{person.age}}</p>
            <p>{{person.town}}</p>

            <button class="followButton" id = "button" onclick=unfollow("{{person.bacnet_id}}","{{person.name}}")>
                Unfollow!
            </button>

        </div>

    </li>

      {% endfor %}

</ul>


<script>

    function unfollow(bacnetID, name){
        $('.list-item').off('click');
        var gender = getGender();
        var mode = getMode();
        var layer = getLayer();
        var nameIn = getname();
        var Town = getTown();
        var influencer = getInfluencerChecked();
        var al;
        var au;
        if (ageLower() === "")
            al = 0;
        else
            al = document.getElementById('ageMin').value
        if (ageUpper() === "")
            au = 120
        else
            au = document.getElementById('ageMax').value
        $.ajax({

                type: "POST",
                url: '{{ '' }}',
                async: false,
                data: {csrfmiddlewaretoken: '{{ csrf_token }}', text: "uf"+bacnetID+name, mode : "1unfollow", gender : gender,  layer : layer, name: nameIn, town : Town, influencer : influencer, ageLower : al, ageUpper : au},
                success: function (response){
                    $('#test').html('').replaceWith(response)

                }

            });

    }



    $(".list-item").click(function() {
        location.href = $(this).data('link');
    })











</script>

FrontEnd/socialgraph/templates/socialgraph/about.html
{% extends "socialgraph/base.html" %}
{% block content %}

  <div class="container">
      <h4 class="content-section-title">About</h4>

      <div class="content-section" id="aboutContentSection">


      </div>
  </div>

{% endblock content %}

FrontEnd/socialgraph/templates/socialgraph/profile_update.html
{% extends "socialgraph/base.html" %}
{% block content %}
    <div class="updatePage">
        <div class="container">
            <h4 class="content-section-title">Profile Editor</h4>
            <div class="content-section" id="profileUpdateContentSection">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">

                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" style="width: 100px">Status</span>
                                </div>
                                <input type="text" class="form-control" id='status' name="status" placeholder="type..."
                                       style="margin-top: 0px"
                                       value="{% if node.status is not None %}{{ node.status }}{% endif %}">
                            </div>
                            <p id="d"></p>

                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" style="width: 100px">Birthday</span>
                                </div>
                                <input type="date" id='birthday' name="birthday" class="form-control"
                                       style="margin-top: 0px"
                                       value="{% if node.birthday is not None %}{{ node.birthday }}{% endif %}"/>
                            </div>

                            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                <span class="input-group-text" style="width: 100px">Gender</span>
                                <label class="btn btn-secondary {% if node.gender == "female" %}active{% endif %}"
                                       onclick="hideOther()"
                                       id="gender">
                                    <input type="radio" name="gender" id="female" autocomplete="off"
                                            {% if node.gender == "female" %}
                                           checked="checked" {% endif %} value="female">Female</label>

                                <label class="btn btn-secondary {% if node.gender == "male" %}active{% endif %}"
                                       onclick="hideOther()"
                                       id="gender">
                                    <input type="radio" name="gender" id="male" autocomplete="off"
                                            {% if node.gender == "male" %}
                                           checked="checked" {% endif %} value="male">Male</label>

                                <label class="btn btn-secondary {% if node.gender != 'male' and node.gender != 'female' and node.gender is not None %}active{% endif %}"
                                       onclick="showOther()"
                                       id="gender">
                                    <input type="radio" name="gender" id="other" autocomplete="off"
                                           {% if node.gender != 'male' and node.gender != 'female' and node.gender is not None %}checked="checked"{% endif %}
                                           value="other">Other</label>

                                <input type="text" id='otherGender' name="other" class="form-control"
                                       style="margin-top: 0px; display: none; border-radius: 0px; border: 1px"
                                       placeholder="type..."
                                        {% if node.gender is not None and node.gender != 'male' and node.gender != 'female' %}
                                       value="{{ node.gender }}"
                                        {% endif %}/>
                                <label class="btn btn-secondary {% if node.gender is None %}active{% endif %}"
                                       id="del"
                                       onclick="hideOther();del()">
                                    <input type="radio" name="gender" id="none" autocomplete="off"
                                            {% if node.gender  is None %}
                                           checked="checked" {% endif %} value="">del</label>
                            </div>
                            <p id="d"></p>

                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" style="width: 100px">Country</span>
                                </div>
                                <input type="text" id='country' name="country" class="form-control"
                                       placeholder="type..."
                                       style="margin-top: 0px"
                                       value="{% if node.country is not None %}{{ node.country }}{% endif %}"/>
                            </div>
                            <p id="d"></p>

                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" style="width: 100px">Town</span>
                                </div>
                                <input type="text" id='town' name="town" class="form-control" placeholder="type..."
                                       style="margin-top: 0px"
                                       value="{% if node.town is not None %}{{ node.town }}{% endif %}"/>
                            </div>
                            <p id="d"></p>

                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" style="width: 100px">Languages</span>
                                </div>
                                <input type="text" id='languages' name="language" class="form-control"
                                       placeholder="type..."
                                       style="margin-top: 0px"
                                       value="{% if node.language is not None %}{{ node.language }}{% endif %}"/>
                            </div>
                            <p id="d"></p>

                        </div>
                        <div class="col">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="profilePic">Profile Picture</span>
                            </div>
                            <p id="d"></p>
                            <div class="media">
                                <img class="rounded-circle account-img" id="id_old_image"
                                     src="{{ profile.profile_pic.url }}">
                                <img class="rounded-circle account-img" id="id_new_image" src="#"
                                     style="display: none"/>
                            </div>
                            <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic"
                                   class="upload-btn"
                                   onchange="preview_img(this);">
                            <p id="d"></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-primary" id="save">Save</button>
                            <button type="button" class="btn btn-default" id="cancel"
                                    onclick="location.href='/profile/{{ node.id }}';">
                                Cancel
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
      function preview_img(input) {
        if (input.files && input.files[0]) {
          var src = URL.createObjectURL(input.files[0])
          $('#id_new_image')
              .attr('src', src)
          document.getElementById('id_new_image').style.display = 'inline';
          document.getElementById('id_old_image').style.display = 'none';
        }
      }

      function showOther() {
        document.getElementById('otherGender').style.display = 'inline';
        console.log("show");
      }

      function hideOther() {
        document.getElementById('otherGender').style.display = 'none';
        console.log("hide");
      }

      function del() {
        document.getElementById('otherGender').value = '';
      }

    </script>
{% endblock content %}